import { Link } from "@/i18n/routing";
import { Navigation } from '@/components/ui/Navigation';

export default function SecurityPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navigation />
      <main className="flex-1 container mx-auto px-4 py-24 max-w-3xl">
        <h1 className="text-4xl font-bold mb-8">Security</h1>
        <div className="space-y-6 text-muted-foreground">
          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">1. Asset Protection</h2>
            <p>BuatinCSV prioritizes the security of your unreleased intellectual property. In the default Guest Mode, files are never uploaded to any centralized server. They are processed entirely within the memory of your local device browser.</p>
          </section>
          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">2. Export Security</h2>
            <p>The CSV files generated by this application are sanitized to mitigate formula injection attacks in spreadsheet software. If a text field begins with `=`, `+`, `-`, or `@`, it is safely mitigated before export.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
